### ISSUE TITLE
[Feat]: Provide linux-arm64 binary in GitHub Releases

### ISSUE THREAD

**Issue by int128** [Magic-Pod/magicpod-api-client#17]
**Is your feature request related to a problem? Please describe.**
We use the self-hosted runners of arm64 architecture in GitHub Actions. Currently, this project does not provide linux-arm64 binary.

**Describe the solution you'd like**
It would be nice if linux-arm64 binary is provided.

Thanks.

**Comment by nkns165** [comment]
@int128 Thank you for your request and sorry for our late response. We're going to handle it in a couple of weeks.

**Comment by nkns165** [comment]
Since the latest release [1.2.0.1](https://github.com/Magic-Pod/magicpod-api-client/releases/tag/1.2.0.1), we started to provide linux-arm64 binary. Please try it.

I'm closing this issue.

**Comment by nkns165** [comment]
Since MagicPod 1.3.0, you can download magicpod-api-client linux arm64 binary by Web API.
Please try the following commands.

```
export MAGICPOD_API_TOKEN=[YOUR_API_TOKEN]
export FILE_NAME=magicpod-api-client
curl -L "https://app.magicpod.com/api/v1.0/magicpod-clients/api/linux_arm64/latest/" -H "Authorization: Token ${MAGICPOD_API_TOKEN}" --output ${FILE_NAME}.zip
```

**Comment by int128** [comment]
@nkns165 I confirmed the new release works in our arm64 runner. Thanks a lot!

```yaml
jobs:
  run-magic-pod:
    runs-on: my-arm64-runner
    steps:
      - run: |
          curl -L "https://app.magicpod.com/api/v1.0/magicpod-clients/api/linux_arm64/latest/" -H "Authorization: Token ${MAGICPOD_API_TOKEN}" --output magicpod-api-client.zip
          unzip -q magicpod-api-client.zip
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGICPOD_API_TOKEN }}
      - run: ./magicpod-api-client batch-run --help
```
